HospitalCosts <- read_excel("C:/Users/mypc/Desktop/Simpli Learn/R/HospitalCosts.csv")
View(HospitalCosts)
summary(HospitalCosts)
AGE(HospitalCosts)
hist(HospitalCosts$AGE)
summary(as.factor(HospitalCosts$AGE))
aggregate(TOTCHG~AGE,FUN = sum,data = HospitalCosts)
max(aggregate(TOTCHG~AGE,FUN = sum,data = HospitalCosts))
which.max(summary(as.factor(HospitalCosts$APRDRG)))
diagnosiscost<-aggregate(TOTCHG~APRDRG,FUN = sum,data = HospitalCosts)
diagnosiscost
diagnosiscost[which.max(diagnosiscost$TOTCHG),]
summary(as.factor(HospitalCosts$RACE))
head(HospitalCosts)
HospitalCosts<-na.omit(HospitalCosts)
HospitalCosts$RACE<-as.factor(HospitalCosts$RACE)
HospitalCosts$RACE<-as.factor(HospitalCosts$RACE)
model<-aov(TOTCHG~RACE,data = HospitalCosts)
model
summary(model)
summary(HospitalCosts$RACE)
model1<-lm(TOTCHG~AGE+FEMALE,data = HospitalCosts)
HospitalCosts$FEMALE<-as.factor(HospitalCosts$FEMALE)
model1<-lm(TOTCHG~AGE+FEMALE,data = HospitalCosts)
summary(model1)
summary(HospitalCosts$FEMALE)
head(HospitalCosts)
HospitalCosts$RACE<-as.factor(HospitalCosts$RACE)
model2<-lm(TOTCHG~AGE+FEMALE+RACE,data = HospitalCosts)
summary(model2)
model3<-lm(TOTCHG~.,data = HospitalCosts)
summary(model3)
